### ISSUE TITLE
Add New Mob to MobCollector

### ISSUE THREAD

**Issue by EnderLight3336** [Slimefun-Addon-Community/Supreme#25]
I suggest add a new collector recipe,use GOLD_INGOT or other things to collector slimefun item  STRANGE_NETHER_GOO when the Piglin around the machine,it will be more useful

**Comment by RelativoBR** [comment]
A good idea, it should help the gameplay together with other addon, we will include your suggestion.

**Comment by RelativoBR** [comment]
https://github.com/Slimefun-Addon-Community/Supreme/pull/31
