### ISSUE TITLE
Quarry stops working when server restarts

### ISSUE THREAD

**Issue by RelativoBR** [Slimefun-Addon-Community/Supreme#28]
User Report: The players are telling me that the quarry when the server restarts they stop working, so they have to remove and put it back to work again, there is a solution for that.

![image](https://user-images.githubusercontent.com/36118424/210662299-7006c9a2-01ba-4b38-928f-1c91bcb21721.png)

![image](https://user-images.githubusercontent.com/36118424/210661988-f5e22878-00ad-463b-8ca9-717d41311e3f.png)

**Comment by SchnTgaiSpock** [comment]
are there any error logs on server start?

**Comment by RelativoBR** [comment]
Closed as there are no evidence details, and the bug cannot be reproduced.
