### ISSUE TITLE
Performance supreme generator mob

### ISSUE THREAD

**Issue by RelativoBR** [Slimefun-Addon-Community/Supreme#29]
User Report: I'm having a problem with the supreme generator, the supreme machines are causing a lot of lag on the server

![image](https://user-images.githubusercontent.com/36118424/210672396-d62edd4e-1591-4485-8cc4-9d906071eee3.png)

![image](https://user-images.githubusercontent.com/36118424/210672413-7a19da1e-db72-41d7-94d8-99a055029ba2.png)

**Comment by JustAHuman-xD** [comment]
Any chance you could provide a timings report?

**Comment by SchnTgaiSpock** [comment]
pretty sure its this
```java
Bukkit.getScheduler().callSyncMethod(Supreme.inst(),
          () -> l.getWorld().getNearbyEntities(l, mobRange, mobRange, mobRange, predicate).isEmpty())
```
on line 82. the docs mention there is a 10ms latency until the isDone() method returns true, idk if that means it takes 10ms to execute, or 10ms to register that it executed. could also be that getNearbyEntities is just really laggy

**Comment by JustAHuman-xD** [comment]
It definitely is that, the best thing to do would be to cache an entity after it finds one and then check if that entity is still existing and still close enough. Only if it's not then does it go to the next one.

**Comment by RelativoBR** [comment]
Solved in another ticket

https://github.com/Slimefun-Addon-Community/Supreme/pull/35
