### ISSUE TITLE
Supreme Auto Crafter

### ISSUE THREAD

**Issue by vctrdrr41** [Slimefun-Addon-Community/Supreme#33]
## Description (Required)
When using the mob collector tools and weapons are required, this being said tried to craft weapons like the iron sword and it only wanted to craft shears. Tried differnet positioning of the items to see if they would craft the sword but still crafted the shears. I then changed the input of the items from the networks pusher system to see if sticks should go in first and still no fix to the issue.

## Steps to reproduce the Issue (Required)
https://youtu.be/kMe56_xspXg

## Expected behavior (Required)
Was expecting to get a sword made so it could be better automated

## Environment (Required)
Spigot 3669
Slimefun Dev 1050
Metric module 28
Java 19

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version: Slimefun 4 Dev 1050
 - Plugin Version: Supreme Dev 20

**Comment by RelativoBR** [comment]
Fix in https://github.com/Slimefun-Addon-Community/Supreme/pull/38
