### ISSUE TITLE
Optimization solve the timings problem in TechGenerator and TechMutation 

### ISSUE THREAD

**Issue by RelativoBR** [Slimefun-Addon-Community/Supreme#36]
**User Report:** Identified a high consumption of server resources by some addon machines, requested an optimization so that the machines can use less resources.

**Info:** TechGenerator 3.29% and TechMutation 3.09%

**Images:**

![image](https://user-images.githubusercontent.com/36118424/230472906-c9d118f9-5fc8-434a-a70f-569aaa36a89f.png)

![image](https://user-images.githubusercontent.com/36118424/230472954-aa952414-0c3b-4d3d-bbbd-37ae6b2f0f05.png)

**Comment by JustAHuman-xD** [comment]
I'll take a look

**Comment by RelativoBR** [comment]
@JustAHuman-xD  Could you check this PR? User who reported asked to include a limiter of 10 machines per chuck, I included this customization option, but with a default value of 100

https://github.com/Slimefun-Addon-Community/Supreme/pull/37

**Comment by SchnTgaiSpock** [comment]
looks like `TechGenerator/TechMutation.validRecipeItem` might be an issue? it is iterating over all the recipes per tick, and the inputs probably wont be changing so often so saving it in a cache might be a better option

**Comment by RelativoBR** [comment]
this makes sense

**Comment by JustAHuman-xD** [comment]
Can you send the entire timings report
Also is this machine async or not?

**Comment by JustAHuman-xD** [comment]
> looks like `TechGenerator/TechMutation.validRecipeItem` might be an issue? it is iterating over all the recipes per tick, and the inputs probably wont be changing so often so saving the recipe in a cache might be a better option

I feel like this isn't the problem as every AContainer machine does this and they don't appear on timings this bad.

**Comment by JustAHuman-xD** [comment]
The main lag is coming from cloning the slimefun item stack

**Comment by JustAHuman-xD** [comment]
https://github.com/Slimefun-Addon-Community/Supreme/blob/d1ff1144752f4cfe4a7f1b57131037f374a2c0fc/src/main/java/com/github/relativobr/supreme/machine/tech/TechMutation.java#L258

Is there any reason that you are calling .clone() for both of these here? I don't think its necessary and that is what is lagging it. I would try removing the clone call and doing some testing.

**Comment by JustAHuman-xD** [comment]
Looks like you also do this in some other blocks, I would recommend removing it from them aswell.

**Comment by RelativoBR** [comment]
ok, i will adjust
