### ISSUE TITLE
Config Option for Basic Lumium Generator, but that generator does not exist

### ISSUE THREAD

**Issue by JustAHuman-xD** [Slimefun-Addon-Community/Supreme#51]
## Description (Required)
There is a config option for the energy and buffer of a basic lumium generator, but said generator does not exist

## Steps to reproduce the Issue (Required)
Look at the config & look at the items made by supreme

## Expected behavior (Required)
Either no config option or for a basic lumium generator

## Server Log / Error Report
N/A (Code issue)

## Environment (Required)
N/A (Code issue)

 - Minecraft Version: N/A (Code issue)
 - CS-CoreLib Version: N/A (Code issue)
 - Slimefun Version: N/A (Code issue)
 - Plugin Version: N/A (Code issue)

**Comment by JustAHuman-xD** [comment]
Didnt even mean lumium i meant thorium but I was looking at the wrong thing, ignore this entire thing LOL

**Comment by Sefiraat** [comment]
Glad I could help fix this issue for you! *cough*

**Comment by JustAHuman-xD** [comment]
> Glad I could help fix this issue for you! *cough*

🤣
