### ISSUE TITLE
Supreme item converter works on nearly all slimefun items, 

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun-Addon-Community/Supreme#55]
the supreme item converter is essentially a free and unlimited anvil, mending and potential duping machine because it works on nearly everything in slimefun. Supreme 2.0 has been out for too long for this item to still be in the plugin. please remove it.

## Server Log / Error Report
no errors

## Environment (Required)

 - Minecraft Version: any
 - CS-CoreLib Version: na
 - Slimefun Version: all versions of sf that work with supreme
 - Plugin Version: all versions of supreme

**Comment by darklord3214** [comment]
what do you  mean by that

**Comment by Boomer-1** [comment]
only going to disucss with Relativo

**Comment by Bunnky** [comment]
There are folks that are still on older versions of the plugin, waiting for a **stable** time to update. I'd much rather see this fixed then outright removed.

**Comment by Boomer-1** [comment]
it's been out for over a year and has been rock solid. if you're on supreme 1.0 still, which wasn't stable, the time to update has been past. players can abuse this converter

**Comment by RelativoBR** [comment]
Fix in:
- https://github.com/Slimefun-Addon-Community/Supreme/pull/56

**Comment by Boomer-1** [comment]
closed as completed.
