### ISSUE TITLE
Forge Magical Machine dont stop

### ISSUE THREAD

**Issue by Dexter041** [Slimefun-Addon-Community/Supreme#58]
## Description (Required)

forge magical machines continue production even if all output slots are full. kinda voiding (input waste). couldnt they stop when full?

## Expected behavior (Required)
a fix in future update.

## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - Plugin Version:

**Comment by RelativoBR** [comment]
Correction related to this PR (https://github.com/Slimefun-Addon-Community/Supreme/pull/70)

**Comment by RelativoBR** [comment]
Fixed in Supreme Build 3
https://blob.build/project/Supreme
