### ISSUE TITLE
Supreme is not working on my server

### ISSUE THREAD

**Issue by nit-in-space** [Slimefun-Addon-Community/Supreme#61]
I have installed supreme in my 1.20.4 paper MC server
with Slimefun 4.
the supreme appeared in my SF inventory but the problem is that any of its components wont work>
For e.g. The supreme capacitor wont store energy.
the supreme generator  wont store energy.. 

Please help me as soon as possible.

**Comment by ReallyNotSomeone** [comment]
Send screenshots of the output if /sf versions, check your console for any errors, and do /pl and send a screenshot of the output

**Comment by ybw0014** [comment]
Issues is not a place to get help. Provide the required information. 80% of the time, the issue is because of the user.

**Comment by Boomer-1** [comment]
update to the latest version. 29 isn't it

**Comment by nit-in-space** [comment]
Its resolved!
Need to change af to dev version and supreme to latest
