### ISSUE TITLE
electrical magical machines allow cetrus items to be made without using all the ingredients

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun-Addon-Community/Supreme#68]
## Description (Required)

setup crafting any cetrus item with all the ingredients.
once the process starts, pull out the core of whatever is being used
the process will produce the cetrus after the timer runs out.

## Expected behavior (Required)

all items to be immediately consumed like they are in core slimefun machines before the timer starts to ensure duping can't be done.

## Environment (Required)

 - Minecraft Version: all. most recently tested in 1.20.1 and 1.20.4
 - CS-CoreLib Version: n/a
 - Slimefun Version: 1156
 - Plugin Version: dev 1

**Comment by SchnTgaiSpock** [comment]
i just tested out crafting a cetrus lumium on 1.20.1. I pulled the nether stars out, and when the timer runs out it tells you to put in more materials in order to craft it, and breaking the machine also doesn't drop the finished product. Which item did you try crafting, and which item did you pull out?

**Comment by SchnTgaiSpock** [comment]
nvm i got it

**Comment by RelativoBR** [comment]
Is being fixed in the PR created by SchnTgaiSpock

- https://github.com/Slimefun-Addon-Community/Supreme/pull/69

**Comment by RelativoBR** [comment]
Correction related to this PR (https://github.com/Slimefun-Addon-Community/Supreme/pull/70)

**Comment by RelativoBR** [comment]
Fixed in Supreme Build 3
https://blob.build/project/Supreme
