### ISSUE TITLE
the version 3 & 4 update broke the use of cargo and networks on all electric machines

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun-Addon-Community/Supreme#76]
## Description (Required)
version 4 of supreme now requires the entire recipe to be in electric core machine, electric fabricator, any machine that needs more than 1 item to process the machine. however that pr could not have been tested properly with cargo or networks. the code of supreme does not allow cargo or networks to fill the machine with more than 1 stack of an item, rendering every supreme machine that fits this case as useless.  

## Steps to reproduce the Issue (Required)
place down an electric core machine. put in one stack of apples and one stack of honey bottles. prior to version 3, the machine would start to process the core. now it won't until all 9 correct stacks are in the machine, which can't happen now with cargo or networks because of the changes, and how supreme is coded for cargo. To fix this cargo has to be able to input all items into the machine properly to make the recipe, or undo what was done with dev 3, and fix it properly so that the machine still requires all items to be in it to finish the recipe. by taking everything at once, everything broke. 

## Expected behavior (Required)
the machine to start immediately upon receiving items where you can't input all the recipe.

## Server Log / Error Report
no errors

## Environment (Required)

 - Minecraft Version: 1.20.4
 - CS-CoreLib Version:
 - Slimefun Version: 1157
 - Plugin Version: 3 and 4

**Comment by RelativoBR** [comment]
-  fix: https://blob.build/dl/Supreme/Dev/5
